server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncodeing=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms  # None
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: admin
    publisher-confirms: true  #如果对异步消息需要回调必须设置为true
    queue:
      name:
        cancelOrder: cancelOrderQueue

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

pagehelper:
  help-dialect: mysql

redis:
  database: 0
  key:
    prefix:
      admin: "ums:admin:"
      resourceList: "ums:resourceList:"
      authCode: "portal:authCode:"
    expire:
      common: 86400  # 1 day
      authCode: 120  # 验证码过期时间

jwt:
  tokenHeader: Authorization  # JWT存储的请求头
  cipher: mall-admin-cipher  # JWT加解密使用的密钥
  expiration: 86400  # JWT的过期时间 (60*60*24) = 1 day
  tokenHead: 'Bearer '  # JWT负载中拿到开头

logging:
  level:
    ROOT: INFO
